version: '2'
services:
  gatewayapplication-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/gatewayApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gatewayApplication
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
